name: CI - Coverage

on:
  push:
    branches: [ master ]
  pull_request: ~
  workflow_dispatch: ~

jobs:
  Coverage_Requirements:
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v3

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x.x

      - name: Set up dotnet tools and dependencies
        run: make install

      - name: Check if test suite coverage meets requirements
        run: make coverage-check

  Upload_Coverage_Report:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v3

      - name: Set up dotnet tools and dependencies
        run: make install

      - name: Generate coverage report
        run: make coverage

      - name: Upload lcov coverage report to Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: coveragereport/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
