name: CI - Compatibility

on:
  push:
    branches: [ master ]
  pull_request: ~
  workflow_dispatch: ~

jobs:
  FSharp_Compatibility:
    runs-on: windows-2022
    steps:

      - uses: actions/checkout@v3
        with:
          submodules: true

        # Install .NET SDK
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x.x
        # Set the project name
      - name: Set up variables
        id: test_project
        run: echo "::set-output name=test_file::EasyPost.Tests.fsproj"

        # Install MSBuild, used to build the test project
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

        # Install NuGet.exe to restore required NuGet packages
      - name: Setup Nuget
        uses: NuGet/setup-nuget@v1.0.5

        # Install Visual Studio's console test application, to execute tests
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

        # Restore required NuGet packages
      - name: Restore NuGet Packages
        run: make restore

        # Pull in fixtures submodule
      - name: Set up dotnet tools and dependencies
        run: make install

        # Build the test project
      - name: Build Solution
        run: msbuild EasyPost.Tests.FSharp\EasyPost.Tests.FSharp.fsproj /p:platform="Any CPU" /p:configuration="Debug" /p:outputPath="bin/Test" /p:target="Rebuild" -restore

  Visual_Basic_Compatibility:
    runs-on: windows-2022
    steps:

      - uses: actions/checkout@v3
        with:
          submodules: true

        # Install .NET SDK
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x.x
        # Set the project name
      - name: Set up variables
        id: test_project
        run: echo "::set-output name=test_file::EasyPost.Tests.vbproj"

        # Install MSBuild, used to build the test project
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

        # Install NuGet.exe to restore required NuGet packages
      - name: Setup Nuget
        uses: NuGet/setup-nuget@v1.0.5

        # Install Visual Studio's console test application, to execute tests
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

        # Restore required NuGet packages
      - name: Restore NuGet Packages
        run: make restore

        # Pull in fixtures submodule
      - name: Set up dotnet tools and dependencies
        run: make install

        # Build the test project
      - name: Build Solution
        run: msbuild EasyPost.Tests.VB\EasyPost.Tests.VB.vbproj /p:platform="Any CPU" /p:configuration="Debug" /p:outputPath="bin/Test" /p:target="Rebuild" -restore
