name: CI - Lint

on:
  push:
    branches: [ master ]
  pull_request: ~
  workflow_dispatch: ~

jobs:
  lint:
    runs-on: windows-2022
    steps:

      - uses: actions/checkout@v3

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x.x

      - name: Set up dotnet tools
        run: make install-tools

      - name: Check style with dotnet-format
        run: make lint
