name: Release

on:
  push:
    tags:
      # ex. "v1.2.3", "v1.2.3-rc1"
      - "v[0-9]+.[0-9]+.*"

jobs:
  publish:
    name: Publish to NuGet
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # todo: unneeded?
      - name: Establish variables
        id: vars
        run: |
          VERSION=${{ github.event.inputs.version || github.ref_name }}
          echo ::set-output name=version::${VERSION}

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          # .NET 3.1 and 5 are deprecated and removed from GitHub Actions, we need to manually install them
          dotnet-version: |
            3.1.x
            5.x.x
            7.x.x

      - name: Setup Nuget
        uses: NuGet/setup-nuget@v1.1.1

      - name: Load NuGet package cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ matrix.framework }}-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore NuGet Packages
        run: make restore

      - name: Set up dotnet tools and dependencies
        run: make install

      - name: Prep certificate imports
        run: mkdir -p certs

      - name: Import authenticity certificate
        run: echo "${{ secrets.AUTHENTICITY_CERT_ENC }}" > certs/authenticity_cert.pfx.enc

      - name: Import signing certificate
        run: echo "${{ secrets.SIGNING_CERT_ENC }}" > cert/signing_cert.snk.enc

      - name: Decrypt certificates
        run: make github-actions-certs-decrypt pass=${{ secrets.ENCRYPTION_KEY }}

      - name: Delete straggling .nupkg files
        run: rm -f *.nupkg || true

      - name: Build NuGet package
        run: make prep-release cert=certs/authenticity_cert.pfx sncert=certs/signing_cert.snk pass=${{ secrets.CERT_PASSWORD }}

      - name: Delete certificates
        run: rm -rf certs

      - name: Publish to NuGet
        run: make publish key=${{ secrets.NUGET_API_KEY }}

      - name: Create a GitHub release
        uses: softprops/action-gh-release@v1
        # ref: https://github.com/softprops/action-gh-release#-customizing
        with:
          body_path: RELEASE_NOTES.md
          files: |
            "*.nupkg"